data:
  dataset_name: NLST
  data_preprocessing_protocol_number: 4
  dimension: 2
  resize: false
  dataloader:
    dataset_name: NLST
    data_preprocessing_protocol_number: 4
    data_type: whole_slice
    data_augmentation:
      apply: false
      augmented_to_original_data_ratio: 2
      parameters:
        number_of_augmentations: 3
        random_rotation_degrees: 10
        random_translation_fraction: 0.1
        random_brightness_intensity_factor: 0.3
        random_contrast_intensity_factor: 0.3
        random_gaussian_blur:
          kernel_size:
          - 3
          - 3
          sigma:
          - 0.1
          - 1.0
        random_gaussian_noise_variance: 0.001
        random_elastic_alpha: 10.0
        random_elastic_sigma: 5.0
    image_numpy_arrays_dir_path: /nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/nlst/preprocessed_data/protocol_4/whole_slice_numpy_arrays
    number_of_k_folds: 3
    seed_value: 22
    test_fraction_of_entire_dataset: 0.2
    torch_dataloader_kwargs:
      batch_size: 16
      num_workers: 8
    validation_fraction_of_train_set: 0.1
    dimension: 2
    resize: false
    roi: lung
    resample: false
    resample_z: false
  metadataframe:
    dataset_name: NLST
    data_preprocessing_protocol_number: 4
    data_type: whole_slice
    label: 5y
    resample: false
    dimension: 2
experiment_execution:
  ids:
    experiment_id: 12
    experiment_version_id: 13
  info:
    who: Maria Amaro
    what: ResNEt502d
  paths:
    experiment_dir_path: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_12
    experiment_version_dir_path: /nas-ctm01/homes/mipaiva/pipeline_template_pl/experiment_results/experiment_12/version_13
    preprocessed_data_dir_path: /nas-ctm01/datasets/public/medical_datasets/lung_ct_datasets/nlst/preprocessed_data
    python_project_dir_path: /nas-ctm01/homes/mipaiva/pipeline_template_pl
hyperparameter_grid_based_execution:
  apply: true
  hyperparameter_combination:
    index: 13
    used:
      model.pytorch_lightning_model.hyperparameters.optimiser.kwargs.lr: 1.0e-07
      data.dataloader.torch_dataloader_kwargs.batch_size: 16
      seed_value: 22
  hyperparameter_grid:
    model.pytorch_lightning_model.hyperparameters.optimiser.kwargs.lr:
    - 0.001
    - 0.0001
    - 1.0e-05
    - 1.0e-06
    - 1.0e-07
    data.dataloader.torch_dataloader_kwargs.batch_size:
    - 16
    - 32
    - 64
    seed_value:
    - 22
model:
  model_id: RN502D
  model_name: ResNet502d
  dimension: 2
  model_pipeline:
    model_id: RN502D
    model_name: ResNet502d
    callbacks:
      model_checkpoints:
      - monitor: val_auroc
        filename: mod=RN502D-exp=X-ver=Y-dtf=Z-{epoch}-var={val_auroc:.3f}
        mode: max
        save_top_k: 1
      - monitor: val_loss
        filename: mod=RN502D-exp=X-ver=Y-dtf=Z-{epoch}-var={val_loss:.3f}
        mode: min
        save_top_k: 1
      - filename: mod=RN502D-exp=X-ver=Y-dtf=Z-{epoch}-var=last_epoch
      model_early_stoppings:
      - monitor: val_auroc
        patience: 50
        mode: max
        verbose: false
    enable_logging: false
    enable_model_early_stopping: true
    finalization:
      delete_model_checkpoints: true
      save_used_data_file_names: false
    pytorch_lightning_model:
      model_id: RN502D
      model_name: ResNet502d
      hyperparameters:
        device: cuda
        number_of_classes: 2
        optimiser:
          type: Adam
          kwargs:
            lr: 1.0e-07
        criterion:
          apply_weights: true
          device: cuda
          metadataframe:
            dataset_name: NLST
            data_preprocessing_protocol_number: 4
            data_type: whole_slice
            label: 5y
            resample: false
            dimension: 2
        model:
          number_of_classes: 2
          dimension: 2
    pytorch_lightning_trainer_kwargs:
      accelerator: gpu
      enable_checkpointing: false
      enable_model_summary: false
      enable_progress_bar: false
      log_every_n_steps: 1
      min_epochs: 0
      max_epochs: 200
  pytorch_lightning_model:
    model_id: RN502D
    model_name: ResNet502d
    hyperparameters:
      device: cuda
      number_of_classes: 2
      optimiser:
        type: Adam
        kwargs:
          lr: 1.0e-07
      criterion:
        apply_weights: true
        device: cuda
        metadataframe:
          dataset_name: NLST
          data_preprocessing_protocol_number: 4
          data_type: whole_slice
          label: 5y
          resample: false
          dimension: 2
      model:
        number_of_classes: 2
        dimension: 2
results_analysis:
  model_test_performance_metrics_dataframe:
    monitored_variables:
    - val_auroc
    - val_loss
    - last_epoch
  model_training_performance_metrics_figure:
    maximum_number_of_epochs: 200
seed_value: 22
wandb:
  project_name: cs_2d_roi_whole_slice_oneclass_756321
  entity: nlst
  name: resnet50_2d
